import type { AreaEntry } from "./areaSeed";

/**
 * Zimbabwe reference area dataset (curated suburbs/areas across the major
 * cities, with spelling/abbreviation aliases). This is an OPTIONAL white-label
 * seed: a deployment serving the Zimbabwe market can re-export this as the
 * curated dataset by setting `CURATED_AREAS` in ./areaSeed.ts to ZIMBABWE_AREAS.
 * See docs/preferred-area-suggestions.md.
 */
export const ZIMBABWE_AREAS: AreaEntry[] = [
  // ── Harare ──────────────────────────────────────────────────────────────
  { name: "Harare CBD", city: "Harare", aliases: ["CBD", "Town", "City Centre", "Central Business District", "Harare Town"] },
  { name: "The Avenues", city: "Harare", aliases: ["Avenues"] },
  { name: "Arcadia", city: "Harare" },
  { name: "Ashdown Park", city: "Harare" },
  { name: "Avondale", city: "Harare" },
  { name: "Avondale West", city: "Harare" },
  { name: "Avonlea", city: "Harare" },
  { name: "Belgravia", city: "Harare" },
  { name: "Belvedere", city: "Harare" },
  { name: "Bluff Hill", city: "Harare", aliases: ["Bluffhill"] },
  { name: "Borrowdale", city: "Harare" },
  { name: "Borrowdale Brooke", city: "Harare" },
  { name: "Borrowdale West", city: "Harare" },
  { name: "Budiriro", city: "Harare" },
  { name: "Chadcombe", city: "Harare" },
  { name: "Chisipite", city: "Harare" },
  { name: "Cranborne", city: "Harare" },
  { name: "Eastlea", city: "Harare" },
  { name: "Emerald Hill", city: "Harare" },
  { name: "Glen Lorne", city: "Harare" },
  { name: "Glen Norah", city: "Harare" },
  { name: "Glen View", city: "Harare", aliases: ["Glenview"] },
  { name: "Greendale", city: "Harare" },
  { name: "Greystone Park", city: "Harare" },
  { name: "Gunhill", city: "Harare" },
  { name: "Hatcliffe", city: "Harare" },
  { name: "Hatfield", city: "Harare" },
  { name: "Helensvale", city: "Harare" },
  { name: "Highfield", city: "Harare", aliases: ["Highfields"] },
  { name: "Highlands", city: "Harare" },
  { name: "Hillside", city: "Harare" },
  { name: "Hogerty Hill", city: "Harare" },
  { name: "Houghton Park", city: "Harare" },
  { name: "Kambuzuma", city: "Harare" },
  { name: "Kensington", city: "Harare" },
  { name: "Kuwadzana", city: "Harare" },
  { name: "Lochinvar", city: "Harare" },
  { name: "Mabelreign", city: "Harare" },
  { name: "Madokero", city: "Harare" },
  { name: "Mainway Meadows", city: "Harare" },
  { name: "Mandara", city: "Harare" },
  { name: "Marimba Park", city: "Harare" },
  { name: "Marlborough", city: "Harare", aliases: ["Malborough"] },
  { name: "Mbare", city: "Harare" },
  { name: "Meyrick Park", city: "Harare" },
  { name: "Milton Park", city: "Harare" },
  { name: "Mount Pleasant", city: "Harare", aliases: ["Mt Pleasant", "Mnt Pleasant"] },
  { name: "Mufakose", city: "Harare" },
  { name: "Newlands", city: "Harare" },
  { name: "Northwood", city: "Harare" },
  { name: "Pomona", city: "Harare" },
  { name: "Prospect", city: "Harare" },
  { name: "Queensdale", city: "Harare" },
  { name: "Rolf Valley", city: "Harare" },
  { name: "Sentosa", city: "Harare" },
  { name: "Strathaven", city: "Harare" },
  { name: "Sunningdale", city: "Harare" },
  { name: "Sunridge", city: "Harare" },
  { name: "The Grange", city: "Harare", aliases: ["Grange"] },
  { name: "Tynwald", city: "Harare" },
  { name: "Vainona", city: "Harare" },
  { name: "Warren Park", city: "Harare" },
  { name: "Waterfalls", city: "Harare" },
  { name: "Westgate", city: "Harare" },
  { name: "Westlea", city: "Harare" },
  { name: "Willowvale", city: "Harare" },

  // ── Greater Harare / satellite towns ────────────────────────────────────
  { name: "Chitungwiza", city: "Chitungwiza" },
  { name: "Norton", city: "Norton" },
  { name: "Ruwa", city: "Ruwa" },
  { name: "Epworth", city: "Epworth" },
  { name: "Domboshava", city: "Domboshava" },

  // ── Bulawayo ────────────────────────────────────────────────────────────
  { name: "Bulawayo CBD", city: "Bulawayo", aliases: ["Bulawayo Town", "Bulawayo City Centre"] },
  { name: "Ascot", city: "Bulawayo" },
  { name: "Barbourfields", city: "Bulawayo" },
  { name: "Bradfield", city: "Bulawayo" },
  { name: "Burnside", city: "Bulawayo" },
  { name: "Famona", city: "Bulawayo" },
  { name: "Hillcrest", city: "Bulawayo" },
  { name: "Hillside (Bulawayo)", city: "Bulawayo", aliases: ["Hillside Bulawayo"] },
  { name: "Khumalo", city: "Bulawayo", aliases: ["Kumalo"] },
  { name: "Mahatshula", city: "Bulawayo" },
  { name: "Malindela", city: "Bulawayo" },
  { name: "Montrose", city: "Bulawayo" },
  { name: "Northend", city: "Bulawayo", aliases: ["North End"] },
  { name: "Nketa", city: "Bulawayo" },
  { name: "Nkulumane", city: "Bulawayo" },
  { name: "Parklands", city: "Bulawayo" },
  { name: "Pelandaba", city: "Bulawayo" },
  { name: "Pumula", city: "Bulawayo" },
  { name: "Queens Park", city: "Bulawayo" },
  { name: "Riverside", city: "Bulawayo" },
  { name: "Selborne Park", city: "Bulawayo" },
  { name: "Suburbs", city: "Bulawayo" },
  { name: "Woodville", city: "Bulawayo" },

  // ── Mutare ──────────────────────────────────────────────────────────────
  { name: "Mutare CBD", city: "Mutare", aliases: ["Mutare Town"] },
  { name: "Chikanga", city: "Mutare" },
  { name: "Dangamvura", city: "Mutare" },
  { name: "Fairbridge Park", city: "Mutare" },
  { name: "Florida", city: "Mutare" },
  { name: "Greenside", city: "Mutare" },
  { name: "Morningside", city: "Mutare" },
  { name: "Murambi", city: "Mutare" },
  { name: "Palmerston", city: "Mutare" },
  { name: "Sakubva", city: "Mutare" },
  { name: "Yeovil", city: "Mutare" },
  { name: "Zimunya", city: "Mutare" },

  // ── Gweru ───────────────────────────────────────────────────────────────
  { name: "Gweru CBD", city: "Gweru", aliases: ["Gweru Town"] },
  { name: "Mkoba", city: "Gweru" },
  { name: "Mtapa", city: "Gweru" },
  { name: "Nashville", city: "Gweru" },
  { name: "Senga", city: "Gweru" },
  { name: "Southdowns", city: "Gweru" },
  { name: "Windsor Park", city: "Gweru" },

  // ── Masvingo ────────────────────────────────────────────────────────────
  { name: "Masvingo CBD", city: "Masvingo", aliases: ["Masvingo Town"] },
  { name: "Mucheke", city: "Masvingo" },
  { name: "Rhodene", city: "Masvingo" },
  { name: "Rujeko", city: "Masvingo" },
  { name: "Target Kopje", city: "Masvingo" },

  // ── Other cities & towns ────────────────────────────────────────────────
  { name: "Beitbridge", city: "Beitbridge" },
  { name: "Bindura", city: "Bindura" },
  { name: "Chegutu", city: "Chegutu" },
  { name: "Chinhoyi", city: "Chinhoyi" },
  { name: "Chiredzi", city: "Chiredzi" },
  { name: "Hwange", city: "Hwange" },
  { name: "Kadoma", city: "Kadoma" },
  { name: "Karoi", city: "Karoi" },
  { name: "Kariba", city: "Kariba" },
  { name: "Kwekwe", city: "Kwekwe" },
  { name: "Marondera", city: "Marondera" },
  { name: "Redcliff", city: "Redcliff" },
  { name: "Rusape", city: "Rusape" },
  { name: "Victoria Falls", city: "Victoria Falls", aliases: ["Vic Falls"] },
  { name: "Zvishavane", city: "Zvishavane" },
];
